[phases.setup]
nixPkgs = ['php81', 'php81Extensions.pdo', 'php81Extensions.pdo_mysql', 'php81Extensions.sqlite3', 'nodejs-18_x']

[phases.install]
cmds = ['echo "Skipping composer install - using manual setup"']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'php -S 0.0.0.0:$PORT'
